(defun csharp-method ()
  ;; Insert a Javadoc method comment outline at the cursor position
  (interactive)

  (beginning-of-line)
  (setq start (point))
  (next-line 1)
  (setq startcomment (point))

  (insert "/// <summary>")
  (c-indent-command)
  (insert "\n///   ")
  (c-indent-command)
  (insert "\n/// </summary>")
  (c-indent-command)
  (insert "\n///")
  (c-indent-command)
  (insert "\n")
  (setq paramdoc (point))

  ;; Parameters
  (goto-char start)
  (search-forward "(")
  (setq start-param (point))
  (search-forward ")")
  (setq end-param (point))
  (goto-char start-param)
  (forward-word 2)
  (backward-char 1)
  (while (< (point) end-param)
    (setq now (point))
    (setq param (current-word))
    (goto-char paramdoc)
    (insert "/// <param name=\"" param "\">")
    (c-indent-command)
    (insert "\n///   ")
    (c-indent-command)
    (insert "\n/// </param>")
    (c-indent-command)
    (insert "\n")
    (c-indent-command)
    (setq paramdoc (point))
    (c-indent-command)
    (goto-char now)
    (forward-word 3)
    (backward-char 1))

  ;; Return statement
  (goto-char start)
  (search-forward "(")
  (backward-word 2)
  (setq returnparam (current-word))
  (cond ((not (equal returnparam "void"))
         (goto-char paramdoc)
         (insert "///")
         (c-indent-command)
         (insert "\n/// <returns>")
         (c-indent-command)
         (insert "\n///   ")
         (c-indent-command)
         (insert "\n/// </returns>")
         (setq paramdoc (point))
         (c-indent-command)
         (insert "\n")
         (c-indent-command)))

  ;; Move entire block above the method name
  (goto-char startcomment)
  (beginning-of-line)
  (setq start (point))
  (search-forward "{")
  (beginning-of-line)
  (kill-region start (point))
  (previous-line 1)
  (yank)

  ;; Move cursor to beginning of comments block
  (search-backward "<summary>")
  (next-line 1)
  (end-of-line)
)



(defun csharp-class ()
  ;; Insert a Javadoc class comment outline at the cursor position
  (interactive)
  (previous-line 1)
  (insert "/// <summary>")
  (c-indent-command)
  (insert "\n///   ")
  (c-indent-command)
  (insert "\n/// </summary>")
  (c-indent-command)
  (insert "\n///")
  (c-indent-command)
  (insert "\n/// <author href=\"mailto:jdreyer@slb.com\">")
  (c-indent-command)
  (insert "\n///   Jacob Dreyer")
  (c-indent-command)
  (insert "\n/// </author>")
  (c-indent-command)
  (previous-line 5)
  (end-of-line))
